classDiagram
%% Interface Implementations
    Serializable <|.. ProductEntity
    SaleableItem <|.. ProductEntity

%% Inheritance Hierarchy
    ProductEntity <|-- Ticket
    ProductEntity <|-- Publication
    Publication <|-- Book
    Publication <|-- Magazine
    Magazine <|-- DiscMag

%% Associations
    ProductEntity "many" --* "many" CartEntity : products

    class CartEntity {
        -Long id
        -Set~ProductEntity~ products
        +void addProduct(ProductEntity product)
        +Long getId()
        +void setId(Long id)
        +Set~ProductEntity~ getProducts()
        +void setProducts(Set~ProductEntity~ products)
    }

    class ProductEntity {
        <<abstract>>
        -Long id
        -Set~CartEntity~ carts
        +Set~CartEntity~ getCarts()
        +void setCarts(Set~CartEntity~ carts)
        +Long getId()
        +void setId(Long id)
        +toString() String
    }

    class Serializable {
        <<interface>>
    }

    class Ticket {
        +String description
        +double price
        +sellItem()
    }

    class Publication {
        <<abstract>>
        -String title
        -double price
        -int copies
        +getPrice() double
        +Publication()
        +Publication(String title, double price, int copies)
        +toString() String
        +equals(Object obj) boolean
        +hashCode() int
    }

    class Book {
        -String author
        +edit()
        +initialize()
        +sellItem()
        +Book()
        +Book(String author)
        +Book(String author, String title, double price, int copies)
        +toString() String
        +equals(Object obj) boolean
        +hashCode() int
    }

    class Magazine {
        -int orderQty
        -Date currentIssue
        +Magazine()
        +Magazine(int orderQty, Date currentIssue, String title, double price, int copies)
        +edit()
        +initialize()
        +sellItem()
    }
    class DiscMag {
        -boolean hasDisc
        +edit()
        +initialize()
        +sellItem()
        +DiscMag()
        +DiscMag(boolean hasDisc, int orderQty, Date currentIssue, String title, double price, int copies)
    }
    class CashTill {
        -double runningTotal
        +CashTill()
        +showTotal()
        +sellItem(SaleableItem item)
    }
    class SaleableItem {
        <<interface>>
        +sellItem()
        +getPrice() double
    }